INHERIT: ./user-documentation/data/configs/osgconnect.yml

docs_dir: ./user-documentation/data/docs/osgconnect

site_name: OSG Connect Docs
site_url: "https://osg-htc.org/"
repo_name: osg-htc/connectbook
theme:
  features:
    - navigation.tabs
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.svg
  custom_dir: overrides


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGUserSchool
      name: OSG User School on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OSGUserSchool
      name: OSG User School on Facebook
