name: Publish to Freshdesk

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  publish:
    # Job name is Greeting
    name: publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Run the update script
        uses: docker://opensciencegrid/osgvo-ubuntu-18.04:latest
        env:
          APIKEY: ${{ secrets.FRESHDESK_APIKEY }}
        shell: bash
        run: |
            echo "[api]" >update/apikey.ini
            echo "apikey = $APIKEY" >>update/apikey.ini
            ./update/update.sh

