name: Publish to Freshdesk
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  publish:
    # Job name is Greeting
    name: publish
    # This job runs on Linux, but with our own container
    runs-on: ubuntu-latest
    container:
      image: docker://opensciencegrid/osgvo-ubuntu-18.04:latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuation file setup
        env:
          APIKEY: ${{ secrets.FRESHDESK_APIKEY }}
        run: |
            pwd
            cd /github/workspace
            echo "[api]" >update/apikey.ini
            echo "apikey = $APIKEY" >>update/apikey.ini
      - name: Run the update script
        run: |
            cd /github/workspace
            ./update/update.sh

